// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIM.Data;

namespace PIM.Migrations
{
    [DbContext(typeof(PIMContext))]
    partial class PIMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PIM.Models.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddrCity")
                        .HasColumnType("VARCHAR(40)");

                    b.Property<string>("AddrNeighbohood")
                        .HasColumnType("VARCHAR(40)");

                    b.Property<string>("AddrNumber")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("AddrType")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("ZipCode")
                        .HasColumnType("VARCHAR(25)");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1L,
                            AddrCity = "São Paulo",
                            AddrNeighbohood = "Republica",
                            AddrNumber = "105B",
                            AddrType = "Rua",
                            PersonId = 1L,
                            ZipCode = "01045001"
                        },
                        new
                        {
                            AddressId = 2L,
                            AddrCity = "São Paulo",
                            AddrNeighbohood = "Pinheiros",
                            AddrNumber = "125",
                            AddrType = "Avenida",
                            PersonId = 2L,
                            ZipCode = "39100000"
                        },
                        new
                        {
                            AddressId = 3L,
                            AddrCity = "Osasco",
                            AddrNeighbohood = "Vila Yara",
                            AddrNumber = "463",
                            AddrType = "Rua",
                            PersonId = 3L,
                            ZipCode = "06026050"
                        });
                });

            modelBuilder.Entity("PIM.Models.Administrator.Administrator", b =>
                {
                    b.Property<long>("AdministratorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.HasKey("AdministratorId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("PIM.Models.Administrator.CarteiraDeTrabalho", b =>
                {
                    b.Property<long>("CarteiraDeTrabalhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AdministratorId")
                        .HasColumnType("bigint");

                    b.HasKey("CarteiraDeTrabalhoId");

                    b.ToTable("CarteiraDeTrabalhos");
                });

            modelBuilder.Entity("PIM.Models.Country", b =>
                {
                    b.Property<long>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<string>("CountryName")
                        .HasColumnType("VARCHAR(35)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1L,
                            AddressId = 1L,
                            CountryName = "Brasil"
                        },
                        new
                        {
                            CountryId = 2L,
                            AddressId = 2L,
                            CountryName = "Brasil"
                        },
                        new
                        {
                            CountryId = 3L,
                            AddressId = 3L,
                            CountryName = "Brasil"
                        });
                });

            modelBuilder.Entity("PIM.Models.PersonModel.Identity", b =>
                {
                    b.Property<long>("IdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataExpedicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrgaoExpedidor")
                        .HasColumnType("VARCHAR(7)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegistroGeral")
                        .HasColumnType("CHAR(10)");

                    b.HasKey("IdentityId");

                    b.ToTable("Identities");

                    b.HasData(
                        new
                        {
                            IdentityId = 1L,
                            DataExpedicao = new DateTime(2000, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrgaoExpedidor = "SSP",
                            PersonId = 1L,
                            RegistroGeral = "190471001"
                        },
                        new
                        {
                            IdentityId = 2L,
                            DataExpedicao = new DateTime(1995, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrgaoExpedidor = "SSP",
                            PersonId = 2L,
                            RegistroGeral = "362932888"
                        },
                        new
                        {
                            IdentityId = 3L,
                            DataExpedicao = new DateTime(2006, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrgaoExpedidor = "SSP",
                            PersonId = 3L,
                            RegistroGeral = "362932888"
                        });
                });

            modelBuilder.Entity("PIM.Models.PersonModel.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("CPF")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PersonName")
                        .HasColumnType("VARCHAR(70)");

                    b.Property<string>("Role")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("SocialName")
                        .HasColumnType("VARCHAR(25)");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1L,
                            BirthDay = new DateTime(1999, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CPF = "65519709076",
                            Email = "ezratmp+lath6@gmail.com",
                            Password = "pass",
                            PersonName = "Mike Wazowski",
                            Role = "USER",
                            SocialName = "null"
                        },
                        new
                        {
                            PersonId = 2L,
                            BirthDay = new DateTime(1985, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CPF = "82124778005",
                            Email = "lengtmp+lue5n@gmail.com",
                            Password = "passWORLD",
                            PersonName = "Mackenzie Mathis",
                            Role = "USER",
                            SocialName = "null"
                        },
                        new
                        {
                            PersonId = 3L,
                            BirthDay = new DateTime(2000, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CPF = "58113438092",
                            Email = "banetmp+nqzlb@gmail.com",
                            Password = "p4ssw0rld",
                            PersonName = "Alexia Calvert",
                            Role = "USER",
                            SocialName = "null"
                        });
                });

            modelBuilder.Entity("PIM.Models.PersonModel.Telephone", b =>
                {
                    b.Property<long>("TelephoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DDD")
                        .HasColumnType("VARCHAR(5)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("VARCHAR(11)");

                    b.HasKey("TelephoneId");

                    b.ToTable("Telephones");

                    b.HasData(
                        new
                        {
                            TelephoneId = 1L,
                            DDD = "011",
                            PersonId = 1L,
                            TelephoneNumber = "99507-9350"
                        },
                        new
                        {
                            TelephoneId = 2L,
                            DDD = "011",
                            PersonId = 2L,
                            TelephoneNumber = "98732-0893"
                        },
                        new
                        {
                            TelephoneId = 3L,
                            DDD = "011",
                            PersonId = 3L,
                            TelephoneNumber = "99970-7434"
                        });
                });

            modelBuilder.Entity("PIM.Models.State", b =>
                {
                    b.Property<long>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateName")
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1L,
                            AddressId = 1L,
                            StateName = "São Paulo"
                        },
                        new
                        {
                            StateId = 2L,
                            AddressId = 2L,
                            StateName = "São Paulo"
                        },
                        new
                        {
                            StateId = 3L,
                            AddressId = 3L,
                            StateName = "São Paulo"
                        });
                });

            modelBuilder.Entity("PIM.Models.User.Contract", b =>
                {
                    b.Property<long>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ContractTerms")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ContractId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("PIM.Models.User.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AccountStatus")
                        .HasColumnType("bit");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            AccountStatus = false,
                            PersonId = 1L
                        },
                        new
                        {
                            UserId = 2L,
                            AccountStatus = true,
                            PersonId = 2L
                        },
                        new
                        {
                            UserId = 3L,
                            AccountStatus = true,
                            PersonId = 3L
                        });
                });

            modelBuilder.Entity("PIM.Models.User.Wallet", b =>
                {
                    b.Property<long>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<double>("WalletBalance")
                        .HasColumnType("float");

                    b.HasKey("WalletId");

                    b.ToTable("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
